DEFECT_INFO = {
    "Porosity": {
        "meaning": "Small gas pockets trapped inside the weld metal.",
        "cause": "Moisture on the workpiece, damp electrode, improper shielding gas coverage, or excessive arc gap.",
        "acceptability": "Not acceptable – reduces weld strength and durability.",
        "explanation": "Porosity occurs when gas becomes trapped in the molten weld pool and solidifies as small holes. In processes like SMAW, this often happens if the electrode contains moisture or if the workpiece surface is not properly cleaned.",
        "recommendation": "Bake electrodes properly, clean the workpiece before welding, maintain correct arc gap, and ensure proper shielding gas coverage.",
    },
    "Spatters": {
        "meaning": "Small droplets of molten metal scattered around the weld area.",
        "cause": "High welding current, unstable arc, improper polarity, or incorrect welding parameters.",
        "acceptability": "Usually cosmetic but may require cleaning and finishing.",
        "explanation": "Spatter occurs when molten metal is expelled from the weld pool due to excessive current or unstable arc conditions. It is common in SMAW and GMAW processes.",
        "recommendation": "Reduce welding current, maintain stable arc length, and ensure correct polarity and parameter settings.",
    },
    "Undercut": {
        "meaning": "Groove formed along the edge of the weld where base metal has melted away.",
        "cause": "Excessive welding current, high travel speed, or incorrect electrode angle.",
        "acceptability": "Unacceptable – weakens the weld and reduces fatigue strength.",
        "explanation": "Undercut occurs when the base metal near the weld toe melts but is not filled with weld metal. This defect is often caused by improper welding angle or excessive current and can significantly weaken the structure.",
        "recommendation": "Reduce welding current, slow down travel speed, and maintain proper electrode angle.",
    },
    "Lack of Fusion": {
        "meaning": "Weld metal fails to properly fuse with the base metal or previous weld bead.",
        "cause": "Low heat input, incorrect electrode angle, or poor welding technique.",
        "acceptability": "Unacceptable – leads to weak joints.",
        "explanation": "Lack of fusion occurs when the weld metal does not properly bond with the base metal. This often results from insufficient heat input or improper electrode positioning.",
        "recommendation": "Increase heat input, adjust electrode angle, and ensure proper welding technique.",
    },
    "Slag Inclusion": {
        "meaning": "Non-metallic slag trapped within the weld metal.",
        "cause": "Failure to remove slag between weld passes or improper welding technique.",
        "acceptability": "Unacceptable – weakens the weld internally.",
        "explanation": "Slag inclusion occurs when flux residue from processes like SMAW becomes trapped in the weld metal instead of being removed between passes.",
        "recommendation": "Clean slag between weld passes and maintain correct welding angle.",
    },
    "Crack": {
        "meaning": "Visible fracture or break in the weld metal.",
        "cause": "High heat input, rapid cooling, residual stresses, or contamination in filler material.",
        "acceptability": "Unacceptable – critical structural defect.",
        "explanation": "Cracks can form due to thermal stresses during cooling or due to improper material compatibility. In welding processes, sudden cooling or contamination can initiate cracking.",
        "recommendation": "Control heat input and cooling rate, ensure clean materials, and use appropriate filler metal.",
    },
    "Improper Weld Bead": {
        "meaning": "Weld bead shape is uneven, lumpy, or not straight.",
        "cause": "Poor welding technique, incorrect speed, or inconsistent arc length.",
        "acceptability": "Usually unacceptable – indicates poor welding quality.",
        "explanation": "Improper bead formation occurs when the weld bead is irregular due to inconsistent welding movement or incorrect parameters.",
        "recommendation": "Maintain steady hand movement, correct welding speed, and stable arc length.",
    },
    "Burn-through": {
        "meaning": "Hole melted completely through the base metal.",
        "cause": "Excessive welding current or very slow welding speed.",
        "acceptability": "Unacceptable – structural failure risk.",
        "explanation": "Burn-through occurs when excessive heat melts through the base material instead of forming a weld bead.",
        "recommendation": "Reduce welding current and increase travel speed.",
    },
    "Excess Reinforcement": {
        "meaning": "Excess weld metal deposited above the weld surface.",
        "cause": "Slow welding speed or excessive filler metal.",
        "acceptability": "May require grinding or finishing.",
        "explanation": "Excess reinforcement occurs when too much weld metal accumulates on the joint surface, leading to uneven weld geometry.",
        "recommendation": "Control filler metal feed and maintain consistent welding speed.",
    },
    "Arc Strike": {
        "meaning": "Unintended arc contact outside the weld joint.",
        "cause": "Accidental striking of the arc on the base metal surface.",
        "acceptability": "Unacceptable – may cause localized hard spots and cracks.",
        "explanation": "Arc strike defects occur when the welding arc touches the base metal outside the intended weld area, causing localized hardening and possible cracking.",
        "recommendation": "Avoid striking the arc outside the weld joint and use proper welding practice.",
    },
    "Good Welding": {
        "meaning": "No visible defects detected in the weld.",
        "cause": "Proper welding parameters and skilled welding technique.",
        "acceptability": "Acceptable weld – meets quality standards.",
        "explanation": "The weld appears structurally sound with proper bead shape and no visible defects.",
        "recommendation": "No corrective action required.",
    },
}
